config/routes.rb
Rails.application.routes.draw do

  resources :video_games, :path => "videogames"
  
  resources :movies
  # Override the underscored path Ex: http://localhost:3000/blogposts instead of http://localhost:3000/blog_posts
  resources :blog_posts, :path => "blogposts"

  resources :teams, only: [:index, :show]

  resources :players, only: [:index]

  resources :home, only: [:index]

  resources :games, only: [:index, :show]

  # Allow routes such as http://localhost:3000/hello_rails/p/1 to work
  #get ':title/p/:id' => "blog_posts#show", :id => /[0-9]+/

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :hometeam, :class_name => 'Team', :foreign_key => 'hometeam_id'
  has_one :awayteam, :class_name => 'Team', :foreign_key => 'awayteam_id'
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true
  validates :position, presence: true
  validates :number, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :publishdate)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = BlogPost.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      render json: @movie
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      render json: @movie
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :content, :publishdate, :rating)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
  
  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/video_games_controller.rb
class VideoGamesController < ApplicationController
  before_action :set_video_game, only: [:show, :edit, :update, :destroy]

  # GET /video_games
  # GET /video_games.json
  def index
    @video_games = VideoGame.all
  end

  # GET /video_games/1
  # GET /video_games/1.json
  def show
  end

  # GET /video_games/new
  def new
    @video_game = VideoGame.new
  end

  # GET /video_games/1/edit
  def edit
  end

  # POST /video_games
  # POST /video_games.json
  def create
    @video_game = VideoGame.new(video_game_params)

    respond_to do |format|
      if @video_game.save
        format.html { redirect_to @video_game, notice: 'Video game was successfully created.' }
        format.json { render :show, status: :created, location: @video_game }
      else
        format.html { render :new }
        format.json { render json: @video_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /video_games/1
  # PATCH/PUT /video_games/1.json
  def update
    respond_to do |format|
      if @video_game.update(video_game_params)
        format.html { redirect_to @video_game, notice: 'Video game was successfully updated.' }
        format.json { render :show, status: :ok, location: @video_game }
      else
        format.html { render :edit }
        format.json { render json: @video_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_games/1
  # DELETE /video_games/1.json
  def destroy
    @video_game.destroy
    respond_to do |format|
      format.html { redirect_to video_games_url, notice: 'Video game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video_game
      @video_game = VideoGame.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_game_params
      params.require(:video_game).permit(:title, :content, :publishdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(blog_post) do |f| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :publishdate %>
    <%= f.datetime_select :publishdate %>
  </div>

  <div class="field">
    Is public?<br />
    <%= f.check_box :ispublished %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
    <div class="container">

      <div class="jumbotron">
        <h1>Game Recaps</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="blogposts/new" role="button">Post New Review</a></p>
      </div>

      <div class="row marketing">
        <% @blog_posts.each do |blog_post| %>
          <div class="col-lg-6">
            <h4><%= link_to blog_post.title, blog_post %></h4>
            <p><%= blog_post.content %></p>
            <p>Published: <%= blog_post.publishdate %></p>
            <p>
              <%= link_to 'Edit Post', edit_blog_post_path(blog_post) %>
              <%= button_to "Delete", blog_post, data: { confirm: 'Are you sure?' },
                :class => "btn btn-danger btn-sm", :method => :delete %>
            </p>
          </div>
        <% end %>
      </div>

    </div> <!-- /container -->

<p id="notice"><%= notice %></p>

<%= content_for(:title, "Blog Posts") %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @blog_post %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog_post.content %>
</p>

<p>
  <strong>Publishdate:</strong>
  <%= @blog_post.publishdate %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/games/index.html.erb
<%= content_for(:title, "Games") %>

<div class="panel panel-default">
  <div class="panel-heading">Games</div>
  <table class="table">
    <thead><tr> <th>Score</th> <th>Date</th> <th>Location</th> </tr></thead>
    <tbody>
      <% @games.each do |game| %>
      <tr>
        <td><a href="<%= game_path(game.id) %>"><%= game.score %></a></td>
        <td><%= game.date %></td>
        <td><%= game.location %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>

app/views/players/index.html.erb
<%= content_for(:title, "Players") %>

<div class="panel panel-default">
  <div class="panel-heading">Kansas Roster</div>
  <table class="table">
    <thead><tr> <th>#</th> <th>Player Name</th> <th>Position</th> <th>Height</th> <th>Weight</th> <th>Year</th></tr></thead>
    <tbody>
      <% @players.each do |player| %>
      <tr>
        <th scope="row"><%= player.number %></th>
        <td><%= player.name %></td>
        <td><%= player.position %></td>
        <td><%= player.height %></td>
        <td><%= player.weight %></td>
        <td><%= player.year %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/video_games/_form.html.erb
<%= form_for(video_game) do |f| %>
  <% if video_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video_game.errors.count, "error") %> prohibited this video_game from being saved:</h2>

      <ul>
      <% video_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :publishdate %>
    <%= f.datetime_select :publishdate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_games/edit.html.erb
<h1>Editing Video Game</h1>

<%= render 'form', video_game: @video_game %>

<%= link_to 'Show', @video_game %> |
<%= link_to 'Back', video_games_path %>

app/views/video_games/index.html.erb
    <div class="container">

      <div class="jumbotron">
        <h1>Video Game Reviews</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-lg btn-success" href="videogames/new" role="button">Post New Review</a></p>
      </div>

      <div class="row marketing">
        <% @video_games.each do |video_game| %>
          <div class="col-lg-6">
            <h4><%= link_to video_game.title, video_game %></h4>
            <p><%= video_game.content %></p>
            <p>Published: <%= video_game.publishdate %></p>
            <p>
              <%= link_to 'Edit Post', edit_video_game_path(video_game) %>
              <%= button_to "Delete", video_game, data: { confirm: 'Are you sure?' },
                :class => "btn btn-danger btn-sm", :method => :delete %>
            </p>
          </div>
        <% end %>
      </div>
      <div id="root"></div>
    </div> <!-- /container -->


<p id="notice"><%= notice %></p>

<%= content_for(:title, "Video Game Reviews") %>

app/views/video_games/new.html.erb
<h1>New Video Game</h1>

<%= render 'form', video_game: @video_game %>

<%= link_to 'Back', video_games_path %>

app/views/video_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video_game.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @video_game.content %>
</p>

<p>
  <strong>Publishdate:</strong>
  <%= @video_game.publishdate %>
</p>

<%= link_to 'Edit', edit_video_game_path(@video_game) %> |
<%= link_to 'Back', video_games_path %>