config/routes.rb
Rails.application.routes.draw do

  resources :video_games, :path => "videogames"
  
  resources :movies
  # Override the underscored path Ex: http://localhost:3000/blogposts instead of http://localhost:3000/blog_posts
  resources :blog_posts, :path => "blogposts"

  resources :teams, only: [:index, :show]

  resources :players, only: [:index]

  resources :home, only: [:index]

  resources :games, only: [:index, :show]

  # Allow routes such as http://localhost:3000/hello_rails/p/1 to work
  #get ':title/p/:id' => "blog_posts#show", :id => /[0-9]+/

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :hometeam, :class_name => 'Team', :foreign_key => 'hometeam_id'
  has_one :awayteam, :class_name => 'Team', :foreign_key => 'awayteam_id'
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, presence: true
  validates :position, presence: true
  validates :number, presence: true
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/video_game.rb
class VideoGame < ApplicationRecord
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = BlogPost.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      render json: @movie
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      render json: @movie
    else
      render json: @movie.errors, status: :unprocessable_entity
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :content, :publishdate, :rating)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end
  
  def show
    @team = Team.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/video_games_helper.rb
module VideoGamesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <div class="navbar-wrapper">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Chase's Blog</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Sports
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">NCAAB</li>
                    <li><a href=<%= home_index_path %>>Home</a></li>
                    <li><a href=<%= blog_posts_path %>>Posts</a></li>
                    <li><a href=<%= teams_path %>>Teams</a></li>
                    <li><a href=<%= players_path %>>Players</a></li>
                    <li><a href=<%= games_path %>>Games</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Movies
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Movies</li>
                    <li><a href=<%= movies_path %>>Reviews</a></li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    Games
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Games</li>
                    <li><a href=<%= video_games_path %>>Reviews</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>

    </div>
    </header>
    <div class="container">
    <%= yield %>
    </div>
    <footer>
      <p class="pull-right"><a href="#">Back to top</a></p>
      <p>© 2017 Sinclair, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
  </body>
</html>